project_id = "ehpmvahaixellqfwwyam"

[functions.process-csv-upload]
verify_jwt = false

[functions.refresh-dashboard]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false